export const appsMock = [
  {
    image: '/images/appImage1.svg',
    color: '#E7D1B6',
    title: 'Water',
    description: '#1 in Productivity',
    premium: true,
    profileImg: '/images/lama.svg',
  },
  {
    image: '/images/appImage2.svg',
    color: '#4D4D4D',
    title: 'Asos',
    description: 'We all love shopping',
    premium: true,
    profileIcon: 'Like',
    profileColors: 'bg-gray-900 text-white',
  },
  {
    image: '/images/appImage3.svg',
    color: '#D2EDEF',
    title: 'vercel',
    description: 'Description for vercel',
    premium: true,
    profileImg: '/images/lama.svg',
  },
]

export const screensMock = [
  {
    id: 2,
    image: '/images/Imagescreencast1.svg',
    color: '#E7D1B6',
    title: 'Water',
    description: '#1 in Productivity',
    premium: true,
    profileImg: '/images/lama.svg',
    profileName: 'Water',
  },
  {
    id: 22,
    image: '/images/Imagescreencast2.svg',
    color: '#4D4D4D',
    title: 'Asos',
    description: 'We all love shopping',
    premium: true,
    profileIcon: 'Like',
    profileColors: 'bg-gray-900 text-white',
    profileName: 'Asos',
  },
  {
    id: 27,
    image: '/images/Imagescreencast3.svg',
    color: '#D2EDEF',
    title: 'vercel2',
    description: 'Description for vercel',
    premium: true,
    profileImg: '/images/lama.svg',
    profileName: 'vercel',
  },
  {
    id: 274,
    image: '/images/Imagescreencast4.svg',
    color: '#D2EDEF',
    title: 'vercel3',
    description: 'Description for vercel',
    premium: true,
    profileImg: '/images/lama.svg',
    profileName: 'vercel',
  },
]
