export const attachmentMock = {
  id: '1231231',
  url: '/images/attachmentFull.png',
  collectionName: 'Klarna',
  profileName: 'Klarna',
  tags: ['Trending'],
  from: 'receipts@klarna.com',
  subject: 'Your payment has been received',
  appVersion: '1.1.1',
  category: 'Finance',
  platform: 'iOS, 15.1',
  region: 'Tallin, Estonia',
  uploadDate: '12 October 2021',
  flows: ['Online purchase'],
  components: ['Button', 'Table', 'Delivery address'],
}
