-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."user_checkout_sessions" add column "subscription_plan_id" uuid
--  not null;
