-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."flow_screencasts" add column "screencast_url" text
--  not null;
