-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."subscription_plans" add column "subscription_plan_type" Text
--  not null;
